
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

      <!-- jQuery library (served from Google) -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
      <!-- bxSlider Javascript file -->
      <script src="/js/jquery.bxslider.js"></script>
      <script src="/js/custom.js"></script>
      <!-- bxSlider CSS file -->
      <link href="/css/jquery.bxslider.css" rel="stylesheet" />

    <title>TrueNews</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  </head>

  <body>
  <div class="modalInner">
      <section class="offer">
          <h2>Подпишитесь на новостную рассылку с доступом к аналитике</h2>
          <p>
          <form method='post'>
              <input type="name" name="name" value="Имя, Фамилия"/ >
              <input type="email" name="email" value="Ваш имейл"/>
              <input type="submit" value="Submit"/>
          </form>
          </p>
      </section>
  </div>

    <nav class="navbar navbar-inverse ">
      <div class="container">

          <div class="navbar-header clearboth">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">TrueNews</a></li>
              <?php foreach($categories_names as $categories_name):
                  $category_num= isset($category_num)?$category_num:1;?>
                  <li>
                      <div class="navbar-collapse  navbar-inverse" >
                          <ul >
                              <li ><a href="/politics?category_id=<?=$category_num?>"><?=$categories_name?></li></a>
                              <?php foreach ($category_articles[$category_num] as $category_article) : ?>
                                  <li id="custom_li"><a href="/politics/articles/?article_id=<?=$category_article->getId();?>&amp;category_id=<?=$category_num?>"><?=$category_article->getTitle();?></a></li>
                              <?php endforeach;?>
                          </ul>
                      </>
                  </li>
                <?php $category_num=$category_num+1;?>
              <?php endforeach;?>

                  <li>
                      <div class="navbar-collapse  navbar-inverse" >
                          <ul >
                              <li ><a href="#">Top 5 Feedbackers</li></a>
                              <?php foreach ($top5FeedbackAuthors as $FeedbackAuthor) : ?>
                                  <li id="custom_li"><a href="/feedbacker/?user_id=<?=$FeedbackAuthor->getUserId();?>"><?=$FeedbackAuthor->getUserName().' '.$FeedbackAuthor->getFeedbackCount()?></a></li>
                              <?php endforeach;?>
                          </ul>
                      </>
                  </li>




                  <li>
                      <div class="navbar-collapse  navbar-inverse" >
                          <ul >
                              <br>
                              <br>
                              <li ><a href="#">Top commented Articles</li></a>
                              <?php foreach ($topArticles as $topArticle) : ?>
                                  <li id="custom_li"><a href="/politics/articles/?article_id=<?=$topArticle->getId();?>&amp;category_id=<?=$topArticle->getCategoryId()?>"><?=$topArticle->getTitle()?></a></li>
                              <?php endforeach;?>
                          </ul>
                      </>
                  </li>

              <!-- Example single danger button -->
              <div class="btn-group">
                  <br>
                  <br>
                  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     Analytics
                  </button>
                  <div class="dropdown-menu">
                      <a class="dropdown-item" href="/analytics">Analytics</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="/article_filter/">Article Filter</a>

                  </div>
              </div>



            <?php if (\Library\Session::has('user')) : ?>
                <br>
                <br>
              <li><a href="/logout">Logout (<?=\Library\Session::get('user')?>)</a></li> 
            <?php else: ?>
                <br>
                <br>
              <li><a href="/login">Login</a></li>
            <?php endif ?>
          </ul>
        </div><!--/.nav-collapse -->
      </div>



        <div>

            <form method='post'>
                <select class="form-control" name="search">
                    <option value="" disabled>Tag</option>
                    <?php foreach ($all_tags as $tag):?>
                        <option value="<?=$tag?>"  ><?=$tag?></option>
                    <?php endforeach;?>
                </select>
                <p><input type="submit" value="search by #Tag"></p>
            </form>
        </div>


        <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
        <script>
            $('select').select2();
        </script>
    </nav>






  <div class="container">

        <div class="starter-template">

            <?=\Library\Session::getFlash()?>

            <?=$content ?>


            <!--<h1>Bootstrap starter template</h1>-->
            <!--<p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>-->
        </div>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
        <script src="libs/arcticmodal/jquery.arcticmodal.js"></script>
        <link rel="stylesheet" href="libs/arcticmodal/jquery.arcticmodal.css">
        <link rel="stylesheet" href="libs/arcticmodal/themes/simple.css">
        <script src="//yandex.st/jquery/cookie/1.0/jquery.cookie.min.js"></script>
        <script src="libs/arcticmodal/config.js"></script>


        <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/js/bootstrap.min.js"></script>


  </body>


</html>


